project:
  type: website
  output-dir: docs

website:
  title: "temp_website"
  favicon: favicon.png
  navbar:
    logo: \docs\SIT-logo.png
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Project
      - href: video.qmd
        text: Fav movie
      
    

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: left

editor: visual

